### ISSUE TITLE
No highlighting on fresh VS2017 installation

### ISSUE THREAD

**Issue by dandy-step** [samizzo/nshader#17]
I've been reading the previous issues and trying every solution, including disabling all the other extensions and reinstalling VS2017 Community (15.3.5). The issue is that no highlighting ever appears on my shader files, and there is no nShader section under Options although "Shader Language" does appear under the Text Editor section. Enabling, disabling, and reinstalling the extension doesn't seem to do anything either, except that with the extension enabled I get no highlighting at all and with it disabled I get the basic highlighting. Opening the file through a solution, manually, or creating a new shader file results in the same thing.

The extension appears in About section, and there are no errors. Going through the activity log and searching for "nShader" yields zero results. Don't really know where to go from there.

![screenshot 686](https://user-images.githubusercontent.com/29162970/30784706-5d1bfea6-a152-11e7-87b7-889c269f5c4e.png)

**Comment by Schmerzmittel** [comment]
I have the same issue.

**Comment by ghost** [comment]
Same issue here, VS2017 Enterprise 15.4, got the "Shader Language" title under 'Options->Text Editor', but no highlight in editor view, no 'Nshader- ...' titles under 'Options->Environment->Fonts and Colors'.

**Comment by themike10452** [comment]
Same here with VS2017 Enterprise 15.3.4

**Comment by ghost** [comment]
Same issue on Community 15.4.2. Hoping this gets fixed soon.

**Comment by Schmerzmittel** [comment]
Let us just clone the repo, debug the source, and pull request?

**Comment by marshal-it** [comment]
can used for vs2017?

**Comment by felixkraas** [comment]
Same here, 
VS 15.4.4
NShader 2.4

**Comment by MStachowicz** [comment]
Fixed mine by manually adding the file extensions under Options->Text Editor->File Extension.
This is on VS community 2017 5.4.4/NShader 2.4

![pxpm3eswt96jxjkpf58uow](https://user-images.githubusercontent.com/14092934/33239949-48b030ac-d2a5-11e7-8c71-6695a1beff9c.png)

**Comment by bakeunbin** [comment]
MStachowicz Could you tell us what version of VS you are using? I have tried that, but it didn't fix the problem for me.

**Comment by MStachowicz** [comment]
@Schmerzmittel Hey VS is community 2017 15.4.4 using NShader 2.4

**Comment by bakeunbin** [comment]
Okay, guys. I think I figured out something. My VS was in different language. When I changed it to English, the shader started to work again. I don't know how many of you are using VS in different language, but if you are using VS in different language, maybe you can change it to English.

**Comment by DianaNites** [comment]
Same issue here. Visual Studio is using English.

Mapping the extensions to NShader did not work.

**Comment by rienik** [comment]
Same here, the .fs file extension had a bit of highlighting before using NShader, after adding .fs to the list it became just plain white text in the editor.

**Comment by rienik** [comment]
I checked the install log and it said: 
`Skipping 'C:\Users\<username>\AppData\Local\Microsoft SDKs' as if it doesn't exist
The extension with ID 'NShader.51a01e9d-eb56-4ee2-a9fd-8212bf6bf2b1' is not installed to Visual Studio Community 2017.` 
So I added the folder 'Microsoft SDKs' to '\AppData\Local\\', reinstalled it, **and it worked!** Although the install log still said:
`The extension with ID 'NShader.51a01e9d-eb56-4ee2-a9fd-8212bf6bf2b1' is not installed to Visual Studio Community 2017.`

**Comment by DianaNites** [comment]
@rienik Thanks, i can confirm that fixed the issue for me as well.

**Comment by johannesugb** [comment]
@rienik Dang, that works indeed! Maybe some additional info: Highlighting used to work until I updated Visual Studio 2017 some days ago. Also installed the latest Windows SDK in addition to previously installed Windows SDKs. Afterwards highlighting was not working anymore.

**Comment by themike10452** [comment]
@rienik your solution works for me as well. Thanks.

**Comment by DianaNites** [comment]
The issue seems to have reappeared for me. Highlighting has disappeared

**Comment by johannesugb** [comment]
Same here: the issue has reappeared even though `Microsoft SDKs` folder is still there and I could not see any errors in the install log. 

Currently, it is working again (by accident?). I have uninstalled and installed it three times in a row. I have no idea, why it behaves that way. Does Visual Studio write to a logfile about problems with extensions?

**Comment by johannesugb** [comment]
Happened again after Windows update KB4074588. `Microsoft SDKs`  folder was gone => re-created it, re-installed NShader => worked again.

**Comment by ForeverZer0** [comment]
I am rather certain this is extension is simply broken on VS2017. 

- Brand new update to VS2017 Enterprise 15.7.3
- Created "Microsoft SDKs" folder in my "AppData/Local" directory
- Installed latest NShader VSIX (2.4)
- Added "frag" and "vert" to open with Nshader in "Tools->Options->Text Editor->File Extension"
- Open "*.frag" and "*.vert" file in VS after restarting and.... NOTHING! No highlighting, no nothing. Might as well just be a regular text document.

**Comment by samizzo** [comment]
Sorry I just haven’t had time to maintain this lately. I would suggest you give HLSL Tools a try https://github.com/tgjones/HlslTools

 I’m also happy to take pull requests that fix bugs. I won’t have time to look at these bugs for another couple of months at the earliest.

**Comment by johannesugb** [comment]
Thanks for you work and you comments, @samizzo !
HlslTools do not provide GLSL highlighting, do they?
